"""accountwatch audit log reader and exporter."""

import csv
import json
import sys
from pathlib import Path

AUDIT_LOG_PATH = Path.home() / ".ghostline" / "accountwatch" / "audit.log"


def _load_events() -> list:
    if not AUDIT_LOG_PATH.exists():
        return []
    events = []
    with open(AUDIT_LOG_PATH, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    events.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return events


def export_audit_log(fmt: str, output_path: str | None) -> None:
    events = _load_events()
    if not events:
        print("[accountwatch] No events in audit log.")
        return

    out = open(output_path, "w") if output_path else sys.stdout

    try:
        if fmt == "json":
            json.dump(events, out, indent=2)
        elif fmt == "csv":
            writer = csv.DictWriter(out, fieldnames=["timestamp", "platform", "added", "removed", "modified"])
            writer.writeheader()
            for e in events:
                writer.writerow({
                    "timestamp": e["timestamp"],
                    "platform": e["platform"],
                    "added": "; ".join(e.get("added", [])),
                    "removed": "; ".join(e.get("removed", [])),
                    "modified": "; ".join(e.get("modified", [])),
                })
        elif fmt == "legal":
            out.write("ACCOUNTWATCH AUDIT LOG — LEGAL EXPORT\n")
            out.write("Generated by Ghostline accountwatch (ghostline.dev)\n")
            out.write("=" * 60 + "\n\n")
            for e in events:
                out.write(f"Timestamp : {e['timestamp']}\n")
                out.write(f"Platform  : {e['platform']}\n")
                if e.get("added"):
                    out.write(f"ADDED     : {', '.join(e['added'])}\n")
                if e.get("removed"):
                    out.write(f"REMOVED   : {', '.join(e['removed'])}\n")
                out.write("-" * 40 + "\n")
    finally:
        if output_path:
            out.close()
            print(f"[accountwatch] Exported {len(events)} event(s) to {output_path}")
